### ISSUE TITLE
Fix README file syntax

### ISSUE THREAD

**Issue by Muhammad-Yazdian** [FidalMathew/ROLL-THE-DICE#13]
Change HyperText format to Github Markdown format.

**Comment by FidalMathew** [comment]
@Muhammad-Yazdian can you explain?

> Change HyperText format to Github Markdown format.

**Comment by Muhammad-Yazdian** [comment]
Here is a guideline for [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for README files.

**Comment by FidalMathew** [comment]
Got it! 👍
